name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
            cd url-shortener &&
            git pull origin main &&
            sudo docker stop app &&
            sudo docker build -t app . &&
            sudo docker run --rm -d -v app-storage:/rails/storage -p 3000:3000 --env RAILS_MASTER_KEY=${{secrets.RAILS_MASTER_KEY}} app
          '
