name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
            cd url-shortener &&
            git pull origin main &&
            bundle install --without development test &&
            RAILS_ENV=production bundle exec rails db:migrate &&
            mkdir -p tmp/pids tmp/sockets log &&
            RAILS_ENV=production bundle exec puma -C config/puma.rb -d
            echo "Deployment completed successfully"
          '
